# Generated by Django 3.2.7 on 2021-09-17 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_alter_tweet_usrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='usrName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
